### PR TITLE
[WIP] Testing

### PR DESCRIPTION
**Pull request by clsource**
This is just a sample testing prototype:

- Using https://github.com/avajs/ava for test runner
- Using https://github.com/developit/microbundle to bundle files
- Changed code to src directory
- Changed dist as the distribution directory
- Separated `createElement` to different files (html, object, svg)
- Changed functions to arrow functions
- Changed to CommonJS `require` instead of exports.

Some ideas to test and thinker with, does not mean to be merged.

### CODE REVIEW

**Comment by mudgen** [comment]
I looked at this pull request thoroughly.  I like a lot of things in it. I'm making a lot of the suggested changes.

I am adding ava and microbundle to the project. 

It looks like microbundle supports ES6 Module export/import syntax because it uses rollup, so I'm going to keep that.  But we will have microbundle export all of its formats including CommonJS.

**Comment by mudgen** [comment]
Does objectCreateElement need to append boolean values to `element.value`?  Because the `addChild` function prevents this.

**Comment by clsource** [comment]
> Does objectCreateElement need to append boolean values to `element.value`? Because the `addChild` function prevents this.

In the testing the value property was needed because otherwise string values would be appended as child (in array) and not a value.

```
const out = div(p("hello world"));

  const child = out.children[0];

  t.is(child.value, "hello world");
```

**Comment by mudgen** [comment]
Okay, great, thanks.

**Comment by mudgen** [comment]
Hey there,
I made some of the suggested changes.

1. I added microbundle.  It now produces many file formats in the dist directory.

I made other changes as well.

I'm not bundling the createElement.js files with webscript.js because I think in lots of cases webscript.js will be used with a library. Also, it is simple to import the other files, for example like this:
```javascript
import builders from 'webscript/dist/webscript.js'
import createElement from 'webscript/dist/createDOMElement.js';
const { div, header, p, a, img, code } = builders(createElement);
```
Thank you so much for your pull request. It was helpful.

**Pull request closed without merging**
