### PR TITLE
Fixed Readme

### PR DESCRIPTION
**Pull request by clsource**
- Changed the format to `asciidoc` to get automatic table of contents.
- Fixed missing image for the example.

### CODE REVIEW

**Comment by mudgen** [comment]
Thanks for this. I will merge this in.  I am doing a significant amount work on the documentation right now.  Essentially it will replace much of the readme with a simple documentation website.  I am very happy for you to take a look at it when I finish initial work on it.

**Comment by clsource** [comment]
I know that you are using jekyll. I would recommend taking a look to docsify https://docsify.js.org/ since it does not require additional tools to test it in local :)

**Comment by mudgen** [comment]
Thank you.  I took a look at Docsify and I like it.

I tried out jekyll and decided to make the documentation website just using Webscript.  

I am still working on the documentation, but here it is at this point: https://mudgen.github.io/webscript/docs/

@clsource I really appreciate your help and I am excited to see where we take it.

**Comment by clsource** [comment]
@mudgen seems like a good idea. Using Webscript to document Webscript. An example of "Eat Your Own Dog Food". 👍

**Pull request merged**
